### PR TITLE
feat(generate): feed output in generate folder BREAKING CHANGE

### LINKED ISSUE #41: feed output in static folder
Why is the plugin writing the feeds into the `static` folder?
I would expect the files to only show up in the `dist` folder.

### LINKED ISSUE #47: Path option assumes default static folder location
The feed file in generated under the default /static directory. However, if a different static folder is specified in the config file under dir: { static: }, that is ignored.

### PR DESCRIPTION
**Pull request by ricardogobbosouza**
Update module
- update dependencies
- update badges
- remove babel config

BREAKING CHANGE
- Feed output in generate folder

Resolve #41 
Resolve #47
Resolve #49 
Resolve #50 
Resolve #52 
Resolve #53
Resolve #54
Resolve #55

### CODE REVIEW

**Comment by manniL** [comment]
This *is* a breaking change as the generation timing is moved from "before generation" to "after generation".

**Comment by ricardogobbosouza** [comment]
@manniL yeah

**Comment by manniL** [comment]
@ricardogobbosouza 	Could you fix the conflicts? I'll merge afterwards :+1:

**Comment by ricardogobbosouza** [comment]
ping @manniL

**Comment by manniL** [comment]
Thanks!

**Comment by miteyema** [comment]
@manniL @ricardogobbosouza Hi guys, can you make a new release of this merged commit? I think `v1.1.0` still has the problem of the file being generated directly into the static folder...

**Pull request merged**
