### PR TITLE
feat: nuxt 3 support

### LINKED ISSUE #106: Nuxt 3 Support
There is a nice initiative from @maciejpedzich already: https://github.com/maciejpedzich/nuxt-feed-module/

The upstream issue to consider merging: https://github.com/maciejpedzich/nuxt-feed-module/issues/1

/cc @manniL

### PR DESCRIPTION
**Pull request by nozomuikuta**
This draft PR aims to take over nuxt/framework#103 and resolves nuxt/framework#106.

At first, for the next major release, I triaged all the open issues as below (except Renovate Dependency Dashboard (#99)).

My implementation may include some breaking changes in API, as done in nuxt/framework#103, in a way that I believe is good and beneficial enough for users. I would like to discuss with authors and community while developing this PR.

This PR doesn't aim to add Docus-powered documentation, which is handled in nuxt/framework#103, so that we can keep this PR's "done of definition" manageable.

This PR message will be modified as needed.

## TODOs

- [x] Scaffold by [Nuxt module starter](https://github.com/nuxt/starter/tree/module)
- [x] Restore `LICENSE`
- [x] Restore `CHANGELOG.md`
- [ ] Rewrite `README.md`
- [ ] Restore/Modify Renovate configuration
- [ ] Restore/Modify Commitlint configuration
- [ ] Restore/Modify Husky configuration
- [ ] Restore/Modify testing
- [ ] Restore/Modify GitHub Actions
- [ ] Implement module with new features (✨), breaking changes (⚠️), and bug fixes (🔧)
  - [ ] Feed file generation (blocked by https://github.com/nuxt/nuxt.js/issues/13856)
    - [ ] Atom file generation
    - [ ] JSON file generation
    - [ ] RSS file generation
  - [ ] middleware for feed SSR
  - [ ] cache time for each feed (`async-cache` package is deprecated, can nitro's unstorage layer be an alternative?)
  - [x] create function for each feed
  - [x] data passed to create function for each feed
  - [x] ✨ common create function for all feeds
  - [x] ✨ common data passed to create function for all feeds
  - [x] ✨ #9
  - [ ] ✨ nuxt/framework#70 (need spec)
  - [ ] ✨ nuxt/framework#89 (need spec/research)
  - [ ] ✨ #95 (blocked by https://github.com/jpmonette/feed/issues/98)
  - [x] ⚠️ feed sources factory function (`sources` option can be a function instead of `factory` option)
  - [ ] ⚠️ data passed to feed sources factory function (not sure about use case, can be deprecated (?))
  - [x] 🔧 #63 (fixed by breaking change on `factory` option)
  - [ ] 🔧 nuxt/framework#102 (need research)

## Out of Scope

- Implementation 
  - nuxt/nuxt.js#11733 (looks stale)
  - nuxt/nuxt.js#10961 (looks stale)
- Documentation
  - GraphQL/Apollo example 
    - #5 
    - #11
  - nuxt/bridge#122
  - nuxt/framework#62

### CODE REVIEW

**Comment by provokcx** [comment]
@NozomuIkuta where are you at?

**Comment by nozomuikuta** [comment]
@provok-it 

First of all, don't worry, I do never abandon this PR 🙌 

My PR has been blocked by some issues as described in the PR message.

The biggest one is https://github.com/nuxt/nuxt.js/issues/13856.
If I'm correct, this PR can't be completed without the hook.

@manniL 

Perhaps can we use other hook like one of Nitro instead of `generate` hooks?

---

As for other blockers of new features and bug fixes, [`feed`](https://github.com/jpmonette/feed) package doesn't seem to be so actively developed. Since "done is better than perfect", I'm thinking of postponing new features and bug fixes and focusing on making the module support Nuxt 3 at this moment.

I would like to hear the author's and the the community's thoughts.

---

By the way, JFYR, I'm also creating [an alternative](https://github.com/NozomuIkuta/unfeed) to `feed` package, with which I aim to resolve all the feed-related blockers. If people think it's worth changing the dependency, I could do that at some point (like `@nuxt/feed` v3?). At least, even if `@nuxt/feed` keep depending on `feed`, I would personally publish another feed module powered by my feed generator, just for R&D purpose.

**Comment by TheAlexLichter** [comment]
I agree with the idea to provide a "feature-parity" module with Nuxt 3 support for now and then maybe another major version with a rewrite/revamp ☺️

**Comment by nozomuikuta** [comment]
@manniL 

Thank you for quick response! 😄 

Then, once https://github.com/nuxt/nuxt.js/issues/13856 is resolved or we find another way, I will complete minimal implementation and make this PR ready for review. 🙋‍♂️ 

I appreciate any kinds of help. 🙏

**Comment by TheAlexLichter** [comment]
@NozomuIkuta Maybe we can use a Nitro endpoint that renders the feed? Users can decide then if they want to pre-render it, use SWR or what not ☺️

**Comment by provokcx** [comment]
@NozomuIkuta 
You can probably use the `build` hook since SSG doesn't work in the same way it did in Nuxt 2.
That's what the nuxt/sitemap module does.

What do you think about this @pi0?

**Comment by nozomuikuta** [comment]
@pi0 @danielroe 

Sorry to ask again, but I appreciated if you give us some information based on which we can make decisions about implementation, like we need to await upstream, or we can use a specific hook to achieve our needs.

**Comment by TheAlexLichter** [comment]
@NozomuIkuta  As I mentioned before, I'd go a similar way as you can add sitemaps now. See e.g. [Daniel's blogpost](https://roe.dev/blog/creating-your-own-sitemap-module)

**Comment by nozomuikuta** [comment]
Closed in favor of nuxt/framework#114.

**Pull request closed without merging**
